<a href="https://colab.research.google.com/github/Goseungeun/2026_BigData_Analyst/blob/main/Chapter3_chisquare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 적합도 검정

In [1]:
from scipy import stats

observed = [150,120,30]
expected = [0.5*300,0.35*300,0.15*300]
print(stats.chisquare(observed,expected))

Power_divergenceResult(statistic=np.float64(7.142857142857142), pvalue=np.float64(0.028115659748972056))

In [4]:
# 교차표 데이터 만들기
# 방법 1
import pandas as pd
df = pd.DataFrame({'좋아함':[80,90],
                   '좋아하지않음':[30,10]},
                   index=['남자','여자'])
print(df)

# 방법 2
df = pd.DataFrame([[80,30],[90,10]]
                   ,columns = ['좋아함','좋아하지않음']
                  ,index=['남자','여자'])
print(df)

    좋아함  좋아하지않음
남자   80      30
여자   90      10
    좋아함  좋아하지않음
남자   80      30
여자   90      10

In [5]:
from scipy.stats import chi2_contingency
print(chi2_contingency(df))

Chi2ContingencyResult(statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[89.04761905, 20.95238095],
       [80.95238095, 19.04761905]]))

In [9]:
# 로우 데이터 제공

import pandas as pd
data = {
    '성별': ['남자']*110 + ['여자']*100,
    '운동': ['좋아함']*80 + ['좋아하지 않음']*30 + ['좋아함']*90 + ['좋아하지 않음']*10
}
df = pd.DataFrame(data)
print(df.head(3))

   성별   운동
0  남자  좋아함
1  남자  좋아함
2  남자  좋아함

In [10]:
df = pd.crosstab(df['성별'],df['운동'])
df

운동  좋아하지 않음  좋아함
성별
남자       30   80
여자       10   90

In [11]:
from scipy.stats import chi2_contingency
print(chi2_contingency(df))

Chi2ContingencyResult(statistic=np.float64(9.045792112299468), pvalue=np.float64(0.0026330012530379632), dof=1, expected_freq=array([[20.95238095, 89.04761905],
       [19.04761905, 80.95238095]]))

## 동질성 검정

In [12]:
# 교차표 주어졌을 때
import pandas as pd
from scipy import stats
df = pd.DataFrame([[50,50],[30,70]])
print(stats.chi2_contingency(df))

Chi2ContingencyResult(statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))

In [13]:
# 로우데이터
import pandas as pd
data = {
    '학과': ['통계학과']*100 + ['컴퓨터공학과']*100,
    '동아리가입여부': ['가입']*50 + ['미가입']*50 + ['가입']*30 + ['미가입']*70
}
df = pd.DataFrame(data)
df.sample(5)

         학과 동아리가입여부
102  컴퓨터공학과      가입
46     통계학과      가입
185  컴퓨터공학과     미가입
1      통계학과      가입
161  컴퓨터공학과     미가입

In [14]:
df = pd.crosstab(df['학과'],df['동아리가입여부'])
df

동아리가입여부  가입  미가입
학과
컴퓨터공학과   30   70
통계학과     50   50

In [15]:
from scipy import stats
print(stats.chi2_contingency(df))

Chi2ContingencyResult(statistic=np.float64(7.520833333333334), pvalue=np.float64(0.006098945931214352), dof=1, expected_freq=array([[40., 60.],
       [40., 60.]]))